### ISSUE TITLE
Route error

### ISSUE THREAD

**Issue by bbtfr** [adexin/refinerycms-videojs#20] opened 2013-03-01 09:08 UTC
[Here](https://github.com/adexin-team/refinerycms-videojs/blob/master/config/routes.rb#L4)

No controller defined but there is a route for /videos

**Comment by adexin-team** [comment] 2020-03-02 15:30
Those routes are not supposed to be there (so have been deleted in >= 0.6.2), thus no video or videos page is available, sorry.  It's not perfectly clear what's the expected result would be. You can add videos to your pages via refinerycms website editor (```Add video``` button in wymeditor) or by setting them in your controller decorator and rendering in you views, e.g.:
```ruby
# app/decorators/controllers/refinery/pages_controller_decorator.rb
Refinery::PagesController.class_eval do
  before_action :set_videos, only: [:show]

  private

  def set_videos
    @videos = Refinery::Videos::Video.all
  end
end

```
```html+erb
<%# app/views/refinery/pages/show.html.erb %>
<%= render '/refinery/content_page' %>

<% if defined? @videos %>
<ul>
<% @videos.each do |video| %>
  <li><%= video.to_html %></li>
<% end %>
<ul>
<% end %>
```

Closing since the issue is outdated, feel free to propose any enhancements.

**Closed by adexin-team** 2020-03-02 15:30 UTC
